### ISSUE TITLE
firmware crash shortly after restart

### ISSUE THREAD

**Issue by maks** [wolfeidau/esp32-iotuz#20]
Crash happens within 60sec of restarting.
Building e9a65c5 on ubuntu 16.04 I get:
```
I (10823) mqttservice: Publishing to esp32-02f20/esp/free_heap_size...
[MQTT INFO] Queuing publish, length: 40, queue size(80/4096)

/home/maks/work/iotuz-esp32-firmware/esp-idf/components/freertos/./queue.c:1301 (xQueueGiveFromISR)- assert failed!
abort() was called at PC 0x4008325e
Guru Meditation Error: Core  1 panic'ed (abort)

Backtrace: 0x40009203:0x3ffb11e0 0x40106bc0:0x3ffb1200 0x401070cc:0x3ffb1220 0x40082502:0x3ffb1250 0x40081439:0x3ffb1270

Rebooting...
```
and 
```
xtensa-esp32-elf-addr2line -e build/app-template.elf 0x401070cc
/home/maks/work/iotuz-esp32-firmware/main/./rotaryencoder.cpp:94
```
which is the rotary encoder interrupt handler.

And sure enough commenting out:
https://github.com/CCHS-Melbourne/iotuz-esp32-firmware/blob/master/main/main.cpp#L18

appears to stop the crash from occurring.

Having talked to @wolfeidau about this, he has a theory on why this is happening: due to other things causing the interupt handler to fire that are not the rotary encoder hardware.

**Comment by projectgus** [comment]
Sorry about that! This is fixed as of #21. As it happens the bug wasn't in ISRs or rotary encoder hardware, the sensors task was corrupting the semaphore handle rotary encoder semaphore handle.

'git pull' latest master and it should be fixed.
